ame: Deploy to cPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpanel:
          - name: CPANEL1
            ftp-server: ${{ secrets.CPANEL1_FTP_SERVER }}
            ftp-username: ${{ secrets.CPANEL1_FTP_USERNAME }}
            ftp-password: ${{ secrets.CPANEL1_FTP_PASSWORD }}
          - name: CPANEL2
            ftp-server: ${{ secrets.CPANEL2_FTP_SERVER }}
            ftp-username: ${{ secrets.CPANEL2_FTP_USERNAME }}
            ftp-password: ${{ secrets.CPANEL2_FTP_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      
      # Deploy to cPanel
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ matrix.cpanel.ftp-server }}
          ftp-username: ${{ matrix.cpanel.ftp-username }}
          ftp-password: ${{ matrix.cpanel.ftp-password }}
      
      # Purge CF's cache (optional)
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
