name: Deploy to cPanels
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to Multiple cPanels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to cPanel 1
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.CPANEL1_FTP_SERVER }}
          ftp-username: ${{ secrets.CPANEL1_FTP_USERNAME }}
          ftp-password: ${{ secrets.CPANEL1_FTP_PASSWORD }}
